version: '3.3'

services:

  financescraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financescraper
    restart: always
    volumes:
      - ./data:/app/data 

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    depends_on:
      - financescraper
    ports:
      - "3115:3000"
    volumes:
      - ./data:/metabase-data
